// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrwiobkgtpbfuaglgzxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyd2lvYmtndHBiZnVhZ2xnenh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjU3MzgsImV4cCI6MjA2NTg0MTczOH0.9GUmrH2fQT2K4ejB3T0gTTeJnzLBQ6_qkEm4GnFNbKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);